### ISSUE TITLE
是否可以增加参数，将gemini的安全阈值设置为BLOCK_NONE？

### ISSUE THREAD

**Issue by CatCars** [soulteary/amazing-openai-api#1]
gemini默认的审核过于严格了，完全没有必要。连电影字幕内主角吵架的文本都屏蔽。
在进行翻译工作时经常报错。
https://ai.google.dev/docs/safety_setting_gemini?hl=zh-cn#safety-filters

**Comment by CatCars** [comment]
"threshold": "BLOCK_NONE"

**Comment by soulteary** [comment]
已更新 https://github.com/soulteary/amazing-openai-api/releases/tag/v0.6.2
