### ISSUE TITLE
是否支持gemini-pro-vision

### ISSUE THREAD

**Issue by kokojacket** [soulteary/amazing-openai-api#2]

**Comment by zyxcambridge** [comment]
支持 gpt4V 吗，把 gemini-pro-vision 映射成为 gpt4v；gpt4v的 api 和gpt 不一样的

**Comment by soulteary** [comment]
欢迎贡献仓库，提交代码 :D @kokojacket

**Comment by soulteary** [comment]
> 支持 gpt4V 吗，把 gemini-pro-vision 映射成为 gpt4v；gpt4v的 api 和gpt 不一样的

@zyxcambridge try v0.7.0
